# Generated by Django 5.2.5 on 2025-09-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_counpon_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='counpon',
            new_name='coupon',
        ),
    ]
