# Generated by Django 5.2.5 on 2025-09-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_time',
            new_name='valid_from',
        ),
    ]
